source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'SnapKit', '~> 0.19.1'
pod 'Moya', '~> 6.1.3'
pod 'Moya/RxSwift'
pod 'Argo', '~> 2.2.0'
pod 'Curry', '~> 1.4.0'

